AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "spec/fixtures/**/*"
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: false
  TargetRubyVersion: 3.1
